#!/bin/bash

function print {
    if [ $? -eq 0 ]
    then
        echo -e $1 " \e[1;32mOK\e[0m."
    else 
        echo -e $1 " \e[1;31mNOK\e[0m."
    fi
}

function clean {
    rm -f config.last config.last2 a.out SC
}

cd ../scOOP/

rm -f CMakeCache.txt
rm -rf CMakeFiles/

echo "Building..."

cmake . -DTESTING=ON > /dev/null

make -j4 > /dev/null
mv SC ../Tests/

cd ../Tests/

echo ""
echo "Building comparison version..."
COMPARE_VERSION=$(cat reference_version)

mkdir COMPARISON_VERSION
cd COMPARISON_VERSION/
git clone https://github.com/robertvacha/SC
cd SC/scOOP/
git checkout $COMPARE_VERSION

rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake . -DTESTING=ON > /dev/null

make -j4 > /dev/null

mv SC ../../../SC_reference
cd ../../..

echo ""
echo "testing..., warning: this could take up to 10 minutes"

for name in `ls -d test_*`; do
    cp SC $name/new/
    cd $name/new
    ./SC > log
    cd ../../


    cp SC_reference $name/old/
    cd $name/old/
    ./SC_reference > log
    cd ../../

    diff $name/new/config.last $name/old/config.last > /dev/null
    print $name
done

echo "Pressure Tests: "

cd volumeChange
for name in `ls -d ?h ?l`; do
    cp ../SC $name/new/
    cd $name/new
    ./SC > log
    cd ../../

    cp ../SC_reference $name/old/
    cd $name/old/
    ./SC_reference > log
    cd ../../

    diff $name/new/config.last $name/old/config.last > /dev/null
    print $name
done
cd ..


#./testMPI

