#!/bin/bash

EPS=2

gnuplot <<-EOF

eps=${EPS}

set title 'If sign(eps) == sign(cos(alpha)) then'

unset border
#set xzeroaxis
set yzeroaxis

set yrange [ eps+1: 0.9 ] noreverse nowriteback
set xrange [ -0.1 : pi/2 ] noreverse nowriteback
set xlabel 'Angle between particles [rad]'
set ylabel 'Epsilon multiplicator'

f(x)=x<0.0?1/0:x<pi/2?eps*cos(x)+1:1/0

plot f(x) title ''
pause mouse  keypress

set term png
set output 'parallelEps.png'
replot

EOF
